import Head from "next/head";

export function SEO() {
  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta http-equiv="Cache-control" content="public, max-age=604800" />
      <link rel="icon" href="/favicon.ico" />

      <meta name="description" content="" />
      <meta name="robots" content="index, follow" />
      <meta name="author" content="" />
      <meta name="keywords" content="" />
      <meta name="MobileOptimized" content="320" />
      <meta name="HandheldFriendly" content="True" />
      <meta name="format-detection" content="telephone=no" />

      <meta property="og:title" content="GCB Finance" />
      <meta property="og:description" content="" />
      <meta property="og:locale" content="pt_BR" />
      <meta property="og:type" content="website" />
      <meta property="og:site_name" content="" />
      <meta property="og:site" content="" />

      <meta name="twitter:title" content="" />
      <meta name="twitter:description" content="" />
      <meta name="twitter:site" content="" />
      <meta name="twitter:creator" content="" />
      <meta name="twitter:card" content="summary_large_image" />

      <title>TechMinds</title>
    </Head>
  );
}
